### ISSUE TITLE
how to add a url option to the .toml?

### ISSUE THREAD

**Issue by kayahk** [DuGlaser/git-config-switcher#2]
I am using something like this in my .gitconfig file:
```
[url "git@git.server.com:"]
        insteadOf = https://git.server.com/
```

I tried to add this to the config-switcher .toml file but couldn't figure out how to do it. Can it be done?

Thanks,
Hakan

**Comment by DuGlaser** [comment]
Hi!
Currently, this is not possible, so I will try to make it possible :muscle:

**Comment by DuGlaser** [comment]
@kayahk 
The url option is now available!
But the usage has changed a bit, see the README!
If you have any questions, please ask:pray:

**Comment by kayahk** [comment]
thanks a lot, will test in a bit.
